# Copyright IBM Corp. Todos los derechos reservados.
#
# SPDX-License-Identifier: Apache-2.0
#

# ------------------------------------------------- ----------------------------
# Definicion del nodo order.
# ------------------------------------------------- ----------------------------
OrdererOrgs:
  # ------------------------------------------------- ----------------------------
  # Orderer
  # ------------------------------------------------- ----------------------------
  - Name: Orderer
    Domain: etsiit.ugr.es
    # ------------------------------------------------- ----------------------------
    # "Especificaciones" - Nombre del Host
    # ------------------------------------------------- ----------------------------
    Specs:
      - Hostname: orderer
# ------------------------------------------------- ----------------------------
# "PeerOrgs" - Definici贸n de organizaciones de la red
# ------------------------------------------------- ----------------------------
PeerOrgs:
  # ------------------------------------------------- ----------------------------
  # Organizaci贸n uno: Departamento de Atc.
  # ------------------------------------------------- ----------------------------
  - Name: atc
    Domain: atc.ugr.es
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Organizaci贸n dos: Departamento Decsai.
  # ---------------------------------------------------------------------------
  - Name: decsai
    Domain: decsai.ugr.es
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Organizaci贸n tres: Departamento de Auditoria.
  # -----------------------------------------------------------------------
  - Name: audit
    Domain: audit.ugr.es
    Template:
      Count: 1
    Users:
      Count: 1  
  